sonar.projectKey=benpate_table
sonar.organization=benpate

sonar.sources=.
sonar.exclusions=**/*_test.go,example/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.txt
